### ISSUE TITLE
现在二维码不能扫描了

### ISSUE THREAD

**Issue by liuyongqing1** [yangxuan8282/wechat-remote#1]
我看现在二维码能出来，但是扫描会出现问题。扫描没反应

**Comment by yangxuan8282** [comment]
刚试了一下可以运行啊，itchat 版本是 1.2.16， python 2.7，系统 Debian Jessie，你的系统这几项分别是什么

**Comment by liuyongqing1** [comment]
如何查看itchat  版本 我是昨天安装的pip install itchat 安装的  Python是2.7.9   系统也是debian 8

**Comment by liuyongqing1** [comment]
二维码可以出来但是好像显示 不全。。无法扫描。

**Comment by yangxuan8282** [comment]
```
pip show itchat
```

不是最新版的话，可以升级一下：

```
sudo pip install itchat --upgrade
```

**Comment by liuyongqing1** [comment]
pi@raspberrypi:~$ pip show itchat
---
Name: itchat
Version: 1.2.16
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
是1.2.16的   我窗口是全屏显示的。。但是确实无法扫描。我昨天试了那个网易云音乐的还是可以扫描的。。

**Comment by yangxuan8282** [comment]
显示不全跟系统有关，你可以把 `wechat_remote.py` 倒数第二行

```python
itchat.auto_login(enableCmdQR = True, hotReload = True)
```

改为：

```python
itchat.auto_login(enableCmdQR = 2, hotReload = True)
```

如果是通过一键安装安的话就修改 `/usr/bin/wechat-remote`

另外如果你可以直接访问到目标机器的话，它会把二维码下载到当前文件夹，直接打开图片扫描也行

**Comment by liuyongqing1** [comment]
我尝试一下 感谢

**Comment by liuyongqing1** [comment]
已经可以了 谢谢

**Comment by yangxuan8282** [comment]
那就先关了哈，有问题再开新的就行
